version: '3.9'
services:

  nginx:
    image: nginx
    build: requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - website-vol:/var/www/html
    depends_on:
      - wordpress
    networks:
      - frontend
    restart: unless-stopped

  wordpress:
    image: wordpress
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - website-vol:/var/www/html
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: unless-stopped
    environment:
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}

  mariadb:
    image: mariadb
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - database-vol:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}

volumes:
  database-vol:
    driver: local
    driver_opts:
      device: /home/sdummett/data/database
      type: volume
      o: bind
  website-vol:
    driver: local
    driver_opts:
      device: /home/sdummett/data/website
      type: volume
      o: bind

networks:
  frontend:
  backend:
