version: '3.9'
services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - "/home/sdummett/data/website:/var/www/html"
        #    depends_on:
        #      - wordpress
    networks:
      - frontend
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - "/home/sdummett/data/website:/var/www/html"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: unless-stopped
    environment:
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - "/home/sdummett/data/database:/var/lib/mysql"
    networks:
      - backend
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
    
networks:
  frontend:
  backend:
