version: '3.9'

services:
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
#restart: unless-stopped
        ports:
            - '443:443'
        container_name: nginx_custom_container
